# .gitlab-ci.yml
stages: [test]

image: python:3.12-slim

variables:
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
  POETRY_VIRTUALENVS_CREATE: "false"  # use system env inside the container

cache:
  key: poetry-cache
  paths:
    - .cache/pip/
    - ~/.cache/pypoetry/

before_script:
  - python -m pip install -U pip
  - python -m pip install pipx
  - pipx ensurepath
  - python -m pipx install poetry
  - poetry --version
  - poetry install --no-interaction --no-ansi

test:
  stage: test
  script:
    - if [ -f pytest.ini ] || [ -d tests ]; then poetry run pytest -q; else python -c "print('No tests found, OK')"; fi
  artifacts:
    when: always
    reports:
      junit: junit.xml
    paths:
      - junit.xml
