name: call-central-ci
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  trigger-gitlab:
    runs-on: ubuntu-latest
    env:
      # Hardcode the URL to avoid bad secrets/whitespace issues
      GITLAB_URL: "https://gitlab.com"
      PROJECT_ID: "75144775"   # <- put the real number here
      TOKEN: ${{ secrets.GITLAB_TOKEN }}
      REF: ${{ github.ref_name }}
      LANGUAGE: "python"   # or "python" in the Python repo
      REPO_URL: "https://github.com/${{ github.repository }}"
    steps:
      - name: Trigger GitLab pipeline
        shell: bash
        run: >
          curl --fail -sS -X POST
          -H "PRIVATE-TOKEN: ${TOKEN}"
          --data-urlencode ref=${REF}
          --data-urlencode variables[LANGUAGE]=${LANGUAGE}
          --data-urlencode variables[REPO_URL]=${REPO_URL}
          "${GITLAB_URL}/api/v4/projects/${PROJECT_ID}/pipeline"
